### ISSUE TITLE
each multipolygon

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf-meta#4]
A possible regression occurred when this was added to [turf-centroid and turf-explode](https://github.com/Turfjs/turf-centroid/issues/5).

\cc @tmcw

**Comment by tmcw** [comment]
Sounds more like dependencies are out of date: the "Invalid coordinates" throw was removed from turf-point and shouldn't appear in any dists.

**Comment by tmcw** [comment]
No - turf 1.3.0 doesn't include turf-meta.
