### ISSUE TITLE
geometryEach

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-meta#8]
This should make stuff like https://github.com/Turfjs/turf-to-geometries simple

**Comment by tcql** [comment]
Are you thinking something similar to `coordsEach`, iterating over each geometry in a collection and executes a callback on each?

I'm not sure that sort of `geometryEach` would fit with the intent of to-geometries and to-features. The reasoning behind those two was that if your turf module / algorithm / etc wants to accept _either_ features or geometries, you can ensure that you can always interact with inputted geojson in whichever format is easiest for you internally. 

I think something like `geometryEach` to iterate of each element of Collection (or just "iterate" on a single Geometry, I suppose) could be useful, but I'm not 100% sure whether I would assume that I always want to iterate over all the elements specifically; I may want to retrieve them and do something else. But maybe I'm anticipating something that's unlikely.

EDIT: just occurred to me that you probably meant that `geometryEach` would make the _implementation_ of to-geometries simpler, not that it would somehow be a replacement. I blame lack of coffee before responding
